// ============================================================
// BASE DE DATOS DE EQUIPOS MÉDICOS — Kezelmedica
// Equipos reales del catálogo Red Beat 2026 donde aplica
// (marcados con sku real), complementados con equipo genérico
// donde el catálogo no cubre la categoría (imagenología general,
// hemodiálisis, mobiliario básico).
// ============================================================

export const EQUIPMENT_DATA = [
  // ─── TRANSPORTE / AMBULANCIA ──────────────────────────────
  {
    id: 'camilla-transporte',
    name: 'Camilla de Transporte Plegable',
    brand: 'Kezelmedica',
    area: 'ambulancia',
    category: 'Transporte',
    description: 'Camilla de aluminio de alta resistencia con sistema de plegado rápido. Soporta hasta 250 kg. Ruedas omnidireccionales con freno.',
    features: ['Capacidad 250 kg', 'Plegado en 3 segundos', 'Ruedas de 15 cm con freno', 'Barandales abatibles', 'Compatible con helicóptero'],
    image: null,
    model3d: null,
  },
  {
    id: 'desfibrilador-portatil',
    name: 'Desfibrilador Bifásico Cardio-Aid 360-B',
    brand: 'Cardio-Aid',
    area: 'ambulancia',
    category: 'Cardiología',
    description: 'Desfibrilador bifásico para hospitales y traslados. Identifica arritmias en modo DEA o manual con alertas visuales y sonoras para intervención rápida.',
    features: ['Detección de FV/TV automática', 'Carga a 200 J en ~2.7 s', 'Módulo NIBP SunTech integrado', 'Oximetría Nellcor', 'Capnografía Philips Respironics'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-transporte',
    name: 'Monitor Anyview P1 de Traslado',
    brand: 'Anyview (Red Beat)',
    area: 'ambulancia',
    category: 'Monitoreo',
    description: 'Monitor portátil de la Serie P, diseñado para traslados terrestres y aéreos. Se acopla a la Docking Station para continuar monitoreo sin pérdida de datos al llegar al hospital.',
    features: ['ECG 3/5/12 derivaciones', 'SpO2, PANI, CO2, presión invasiva', 'Docking Station para acople rápido', 'Resistente a caídas de 1 m, IP44', 'Pantalla 5.5"'],
    image: null,
    model3d: null,
  },
  {
    id: 'mochila-trauma',
    name: 'Mochila de Trauma Profesional',
    brand: 'Kezelmedica',
    area: 'ambulancia',
    category: 'Emergencias',
    description: 'Mochila de respuesta rápida con compartimentos organizados para medicamentos, equipos de vía aérea y signos vitales. Material impermeable.',
    features: ['Compartimentos codificados por color', 'Material Nylon 1000D', '35L de capacidad', 'Incluye torniquete y compresas', 'Compatible MOLLE'],
    image: null,
    model3d: null,
  },

  // ─── URGENCIAS ────────────────────────────────────────────
  {
    id: 'camilla-urgencias',
    name: 'Camilla de Urgencias Eléctrica',
    brand: 'Kezelmedica',
    area: 'urgencias',
    category: 'Mobiliario Clínico',
    description: 'Camilla eléctrica de urgencias con ajuste de altura motorizado y respaldo. Superficies antibacteriales. Barandales de seguridad de 3 secciones.',
    features: ['Altura 55–95 cm motorizada', 'Posición Trendelenburg', 'Colchón 10 cm viscoelástico', 'Soporte suero integrado', 'Frenos centralizados'],
    image: null,
    model3d: null,
  },
  {
    id: 'carro-rojo',
    name: 'Carro de Emergencia PRECISO Alupanel',
    brand: 'PRECISO',
    area: 'urgencias',
    category: 'Emergencias',
    description: 'Carro de reanimación PREL8AR-GE-MEX1, estructura ligera anticorrosión con paragolpes perimetral. Amplia superficie para preparación de soluciones.',
    features: ['Cierre centralizado con sigilos de garantía', 'Poste porta venoclisis integrado', 'Soporte desfibrilador giratorio 360°', 'Soporte tanque de oxígeno tipo E', '4 ruedas gemelares antiestáticas 125 mm'],
    image: null,
    model3d: null,
  },
  {
    id: 'desfibrilador-bifasico',
    name: 'Desfibrilador Bifásico Cardio-Aid 360-B',
    brand: 'Cardio-Aid',
    area: 'urgencias',
    category: 'Cardiología',
    description: 'Desfibrilador bifásico manual/DEA para uso en urgencias hospitalarias. Facilita intervención rápida con monitoreo y registro de signos vitales tras reanimación.',
    features: ['Modo DEA y manual', 'Carga a 200 J en ~2.7 s', 'NIBP SunTech integrado', 'Oximetría de pulso Nellcor', 'Capnografía mainstream y sidestream'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-vital',
    name: 'Monitor de Paciente Anyview P12',
    brand: 'Anyview (Red Beat)',
    area: 'urgencias',
    category: 'Monitoreo',
    description: 'Monitor multiparamétrico de la Serie P, galardonada con el Red Dot Design Award 2021. Parámetros estándar de urgencias con opciones avanzadas escalables.',
    features: ['Pantalla 12.1"', 'FC, PANI, SpO2, temperatura, FR, ECG', 'Opcional: PIA, CO2, BIS, SpHb, SpCO', 'Interfaz intuitiva personalizable', 'Uso en cuidado intensivo, emergencia y quirófano'],
    image: '/images/products/anyview-p12.png',
    model3d: null,
  },
  {
    id: 'aspirador-portatil',
    name: 'Aspirador de Secreciones Portátil',
    brand: 'Kezelmedica',
    area: 'urgencias',
    category: 'Vía Aérea',
    description: 'Aspirador de secreciones de alto flujo para manejo de vía aérea en urgencias. Operación con batería recargable y corriente alterna.',
    features: ['Flujo 30 L/min', 'Vacío -80 kPa', 'Batería 45 min', 'Depósito 500 mL reutilizable', 'Silencioso < 68 dB'],
    image: null,
    model3d: null,
  },

  // ─── QUIRÓFANO ────────────────────────────────────────────
  {
    id: 'mesa-quirurgica',
    name: 'Mesa Quirúrgica Motorizada QX-500',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Mobiliario Quirúrgico',
    description: 'Mesa quirúrgica eléctrica de última generación. Control remoto inalámbrico. Múltiples posiciones para todo tipo de cirugías. Tapa radiotransparente.',
    features: ['Control remoto inalámbrico', 'Altura 65–115 cm', 'Inclinación ±30°', 'Tapa radiotransparente', 'Capacidad 320 kg'],
    image: null,
    model3d: null,
  },
  {
    id: 'lampara-cielitica',
    name: 'Lámpara Cielítica LED Doble',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Iluminación Quirúrgica',
    description: 'Lámpara quirúrgica LED de doble cabezal con 160,000 lux de iluminación. Sin sombras, sin calor. Temperatura de color ajustable 3,500–5,000 K.',
    features: ['160,000 lux', 'Temperatura color 3500–5000 K', 'Sin sombras', 'Vida LED 50,000 h', 'Cabezal estéril esterilizable'],
    image: null,
    model3d: null,
  },
  {
    id: 'torre-laparoscopia',
    name: 'Torre de Laparoscopia 4K',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Cirugía Mínimamente Invasiva',
    description: 'Sistema de laparoscopia con cámara 4K Ultra HD. Fuente de luz LED de 300W. Monitor de 31.5" 4K. Compatible con instrumental Karl Storz y Olympus.',
    features: ['Cámara 4K Ultra HD', 'Monitor 31.5" 4K', 'Luz LED 300 W', 'Grabación en USB/red', 'Compatible con principales marcas'],
    image: null,
    model3d: null,
  },
  {
    id: 'maquina-anestesia',
    name: 'Máquina de Anestesia Penlon Prima 460',
    brand: 'Penlon',
    area: 'quirofano',
    category: 'Anestesiología',
    description: 'Sistema de anestesia para adultos, pediatría y neonatos. Plataforma flexible con interfaz táctil y visualización virtual de flujos para quirófanos de alta demanda.',
    features: ['Pantalla táctil HD 15.6"', 'Caudalómetro virtual y mezcla de gases', 'Modos VCV, PCV, PSV, SIMV, PRVC, Manual', 'Batería de respaldo hasta 75 min', 'Absorbedor de CO2 A200SP con calefactor'],
    image: '/images/products/penlon-prima-460.png',
    model3d: null,
  },
  {
    id: 'electrocauterio',
    name: 'Electrocirugía VIO 3',
    brand: 'Erbe',
    area: 'quirofano',
    category: 'Electrocirugia',
    description: 'Nueva generación en electrocirugía de alta precisión, diseñada para un desempeño confiable, preciso y reproducible en cada procedimiento quirúrgico.',
    features: ['Pantalla táctil amplia HD', 'Sistema stepGUIDE de parámetros asistidos', 'Gestión y almacenamiento de programas de usuario', 'Corte y coagulación mono/bipolar', 'Medición exacta y estabilidad constante'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-qx',
    name: 'Monitor de Quirófano Anyview P22',
    brand: 'Anyview (Red Beat)',
    area: 'quirofano',
    category: 'Monitoreo',
    description: 'Modelo de mayor complejidad de la Serie P, con Vista BOA del proceso anestésico completo y monitorización avanzada para quirófano y recuperación.',
    features: ['Pantalla 22", 6 ranuras modulares', 'Vista BOA del proceso anestésico', 'Bloqueo neuromuscular en 7 modos', 'Mecánica respiratoria y oximetría tisular', 'Control por voz (16 comandos)'],
    image: null,
    model3d: null,
  },

  // ─── TRANSPORTE INTERNO ────────────────────────────────────
  {
    id: 'silla-ruedas',
    name: 'Silla de Ruedas Hospitalaria Plegable',
    brand: 'Kezelmedica',
    area: 'transporte_interior',
    category: 'Transporte',
    description: 'Silla de ruedas de uso hospitalario, estructura plegable ligera con reposapiés extraíbles y frenos en ambas ruedas traseras.',
    features: ['Estructura plegable de aluminio', 'Reposapiés extraíbles', 'Frenos en ruedas traseras', 'Capacidad 135 kg', 'Apoyabrazos abatibles'],
    image: null,
    model3d: null,
  },
  {
    id: 'camilla-traslado',
    name: 'Camilla de Traslado Intrahospitalario',
    brand: 'Kezelmedica',
    area: 'transporte_interior',
    category: 'Transporte',
    description: 'Camilla manual para traslado de pacientes entre áreas del hospital. Altura ajustable con pedal hidráulico y barandales abatibles.',
    features: ['Ajuste de altura hidráulico', 'Barandales abatibles de 2 secciones', 'Ruedas de 12.5 cm giratorias', 'Porta expediente y suero', 'Capacidad 180 kg'],
    image: null,
    model3d: null,
  },
  {
    id: 'carrito-medicamentos',
    name: 'Carrito de Medicamentos con Cierre Centralizado',
    brand: 'Kezelmedica',
    area: 'transporte_interior',
    category: 'Transporte',
    description: 'Carrito rodable para distribución segura de medicamentos por piso. Cajones individuales con sistema de cierre centralizado.',
    features: ['Cierre centralizado con llave', 'Cajones individuales etiquetados', 'Superficie de trabajo superior', 'Ruedas silenciosas con freno', 'Estructura de acero inoxidable'],
    image: null,
    model3d: null,
  },

  // ─── TERAPIA INTERMEDIA ───────────────────────────────────
  {
    id: 'cama-electrica-ti',
    name: 'Cama Eléctrica Hospitalaria TI-900',
    brand: 'Kezelmedica',
    area: 'terapia_intermedia',
    category: 'Mobiliario Clínico',
    description: 'Cama hospitalaria eléctrica de 4 funciones para terapia intermedia. Rieles laterales abatibles. Colchón antiescaras opcional.',
    features: ['4 funciones eléctricas', 'Altura 35–80 cm', 'Posición Fowler y Trendelenburg', 'Frenos pediátricos', 'Compatible radiología'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-multiparametrico',
    name: 'Monitor de Paciente Qube',
    brand: 'Spacelabs',
    area: 'terapia_intermedia',
    category: 'Monitoreo',
    description: 'Monitor compacto con pantalla táctil de 12", ideal para pacientes neonatales, pediátricos y adultos de alta complejidad en entornos perioperatorios.',
    features: ['Pantalla táctil de 12"', '96 horas de tendencias gráficas y tabulares', 'ECG de 3, 5 o 12 derivaciones', 'Hasta 8 presiones arteriales invasivas', 'Conexión interactiva de red'],
    image: null,
    model3d: null,
  },
  {
    id: 'oximetro',
    name: 'Oxímetro de Pulso Mighty Sat',
    brand: 'Masimo',
    area: 'terapia_intermedia',
    category: 'Monitoreo',
    description: 'Oxímetro portátil con tecnología Masimo SET Measure-through Motion and Low Perfusion. Pantalla a color giratoria y ajustable para visualización en tiempo real.',
    features: ['SpO2, frecuencia de pulso, Pi, PVi, RRp', 'Pantalla a color giratoria', 'Diseño duradero y ligero', 'Uso clínico y domiciliario', 'Curva de pletismografía en tiempo real'],
    image: null,
    model3d: null,
  },
  {
    id: 'ventilador-ti',
    name: 'Ventilador Mecánico Graphnet Advance',
    brand: 'Kezelmedica',
    area: 'terapia_intermedia',
    category: 'Ventilación',
    description: 'Equipo de ventilación mecánica para pacientes de todas las edades, con soporte respiratorio invasivo y no invasivo fiable y versátil.',
    features: ['14 modos ventilatorios', 'Capnografía volumétrica integrada', 'Batería con duración de 2.5 horas', 'Transporte intrahospitalario', 'Compensación de tubo endotraqueal'],
    image: null,
    model3d: null,
  },

  // ─── ENDOSCOPIA ───────────────────────────────────────────
  {
    id: 'torre-endoscopia',
    name: 'Torre de Endoscopia Full HD',
    brand: 'Kezelmedica',
    area: 'endoscopia',
    category: 'Endoscopia',
    description: 'Sistema de endoscopia completo con procesador de video Full HD. Monitor de 27". Fuente de luz LED integrada. Compatible con instrumental flexible.',
    features: ['Procesador HD 1080p', 'Monitor 27" Full HD', 'LED 250 W', 'Grabación USB/DICOM', 'Compatible Olympus/Pentax'],
    image: null,
    model3d: null,
  },
  {
    id: 'gastroscopio',
    name: 'Broncoscopio Desechable aScope 4 Broncho',
    brand: 'Ambu',
    area: 'endoscopia',
    category: 'Endoscopia',
    description: 'Broncoscopio estéril de un solo uso que elimina el riesgo de desinfección insuficiente propio de los equipos reutilizables. Salida de video a monitor externo.',
    features: ['Dispositivo estéril de un solo uso', 'Disponible en 3 tamaños (Slim/Regular/Large)', 'Canal de trabajo 2.8/2.2/1.2 mm', 'Ángulos de flexión hasta 180°/180°', 'Conector a monitor Ambu aView 2 Advance'],
    image: null,
    model3d: null,
  },
  {
    id: 'colonoscopio',
    name: 'Colonoscopio CF-H290',
    brand: 'Kezelmedica',
    area: 'endoscopia',
    category: 'Endoscopia',
    description: 'Colonoscopio de alta definición con sistema de inserción variable. Longitud de 168 cm. Canal de trabajo de 3.7 mm para polipectomía.',
    features: ['Longitud 168 cm', 'Canal 3.7 mm', 'Inserción variable', 'Ángulo visión 170°', 'Compatible NBI (narrow band)'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-hd-endo',
    name: 'Monitor Endoscopia 4K 32"',
    brand: 'Kezelmedica',
    area: 'endoscopia',
    category: 'Imágenes',
    description: 'Monitor médico 4K de 32 pulgadas diseñado para endoscopia. Reproducción exacta de color. Baja latencia. Certificado médico.',
    features: ['4K Ultra HD', '32 pulgadas', 'Latencia < 20 ms', 'Certificado IEC 60601', 'Soporte HDMI y SDI'],
    image: null,
    model3d: null,
  },

  // ─── SUMINISTRO DE GAS ────────────────────────────────────
  {
    id: 'tanque-oxigeno',
    name: 'Tanque de Oxígeno Medicinal 10m³',
    brand: 'Kezelmedica',
    area: 'suministro_gas',
    category: 'Gases Médicos',
    description: 'Tanque de almacenamiento de oxígeno medicinal de alta presión. Válvula de seguridad integrada. Certificado por COFEPRIS.',
    features: ['Capacidad 10 m³', 'Presión máx 200 bar', 'Válvula de seguridad', 'Certificado COFEPRIS', 'Acero inoxidable 316L'],
    image: null,
    model3d: null,
  },
  {
    id: 'tanque-co2',
    name: 'Tanque de CO2 Medicinal',
    brand: 'Kezelmedica',
    area: 'suministro_gas',
    category: 'Gases Médicos',
    description: 'Cilindro de dióxido de carbono medicinal para insuflación en cirugía laparoscópica y aplicaciones clínicas. Válvula de seguridad certificada.',
    features: ['Uso en laparoscopia e insuflación', 'Válvula de seguridad integrada', 'Certificado COFEPRIS', 'Rotulado normativo NOM-090', 'Compatible con manifold central'],
    image: null,
    model3d: null,
  },
  {
    id: 'regulador-presion',
    name: 'Regulador de Presión de Gas RP-50',
    brand: 'Kezelmedica',
    area: 'suministro_gas',
    category: 'Gases Médicos',
    description: 'Regulador de presión de dos etapas para oxígeno, N2O y aire medicinal. Caudal ajustable de 0–15 L/min.',
    features: ['Dos etapas de regulación', 'Caudal 0–15 L/min', 'Manómetro integrado', 'Conector DISS', 'Compatible todos los gases médicos'],
    image: null,
    model3d: null,
  },
  {
    id: 'manifold-gas',
    name: 'Manifold de Gases Médicos',
    brand: 'Kezelmedica',
    area: 'suministro_gas',
    category: 'Gases Médicos',
    description: 'Panel de distribución de gases médicos con capacidad para 12 cilindros. Conmutación automática entre bancadas.',
    features: ['12 cilindros por bancada', 'Cambio automático', 'Alarma de presión baja', 'Cabezas DISS', 'Aprobado NOM-090'],
    image: null,
    model3d: null,
  },

  // ─── TOCO CIRUGÍA ─────────────────────────────────────────
  {
    id: 'mesa-parto',
    name: 'Mesa de Parto Eléctrica MP-300',
    brand: 'Kezelmedica',
    area: 'toco_cirugia',
    category: 'Obstetricia',
    description: 'Mesa de parto eléctrica con 6 posiciones. Segmento de pierna desmontable. Tapicería antibacterial. Accesorios de quirófano incluidos.',
    features: ['6 posiciones eléctricas', 'Segmento pierna desmontable', 'Altura 62–100 cm', 'Tapicería antibacterial', 'Capacidad 300 kg'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-fetal',
    name: 'Monitor Fetal Electrónico MF-800',
    brand: 'Kezelmedica',
    area: 'toco_cirugia',
    category: 'Obstetricia',
    description: 'Monitor fetal electrónico con cardiotocografía (CTG). Detección de gemelos. Pantalla táctil. Impresora térmica integrada. Conectividad WiFi.',
    features: ['Detección de gemelos', 'Pantalla táctil 10"', 'Impresora térmica integrada', 'WiFi para central', 'Alarmas de FCF'],
    image: null,
    model3d: null,
  },
  {
    id: 'incubadora-neonatal',
    name: 'Incubadora de Traslado TI-2000',
    brand: 'Kezelmedica',
    area: 'toco_cirugia',
    category: 'Neonatología',
    description: 'Incubadora de transporte para traslados terrestres, aéreos o intrahospitalarios del recién nacido, con control preciso de temperatura en modo aire y modo bebé.',
    features: ['Control de temperatura dual (aire/bebé)', 'Suministro de O2 para 2 cilindros', 'Batería 3 h + corriente AC/DC', '4 ventanas de intervención y puerta lateral', 'Carro PT-II de altura ajustable'],
    image: null,
    model3d: null,
  },
  {
    id: 'cuna-termica',
    name: 'Cunero de Calor Radiante Serie 93',
    brand: 'Kezelmedica',
    area: 'toco_cirugia',
    category: 'Neonatología',
    description: 'Unidad de cuidado neonatal con calefacción radiante para brindar un entorno seguro y controlado al recién nacido inmediatamente tras el parto.',
    features: ['3 modos: precalentamiento, manual y bebé', 'Temporizador APGAR audible y visible', 'Conector RS-232 para datos', 'Paneles abatibles y cuna inclinable', 'Acceso rápido para intervención médica'],
    image: null,
    model3d: null,
  },
  {
    id: 'aspirador-neonatal',
    name: 'Aspirador de Secreciones Neonatal',
    brand: 'Kezelmedica',
    area: 'toco_cirugia',
    category: 'Neonatología',
    description: 'Aspirador de baja presión diseñado específicamente para el manejo delicado de vía aérea en recién nacidos durante y después del parto.',
    features: ['Presión regulable de baja intensidad', 'Sondas neonatales incluidas', 'Depósito reutilizable autoclavable', 'Operación silenciosa', 'Montable en cunero o pared'],
    image: null,
    model3d: null,
  },

  // ─── UCIN / UTIP ──────────────────────────────────────────
  {
    id: 'incubadora-neonatal-2',
    name: 'Incubadora Neonatal Fija IN-2000',
    brand: 'Kezelmedica',
    area: 'ucin_utip',
    category: 'Neonatología',
    description: 'Incubadora neonatal de cuidado intensivo con doble pared. Control preciso de temperatura y humedad. Alarmas de desconexión y temperatura.',
    features: ['Doble pared aislante', 'Humedad 30–95%', 'Control servo de piel', 'Acceso de 4 portillas', 'Báscula integrada'],
    image: null,
    model3d: null,
  },
  {
    id: 'ventilador-neonatal',
    name: 'Ventilador Neonatal Graphnet Neo',
    brand: 'Kezelmedica',
    area: 'ucin_utip',
    category: 'Ventilación',
    description: 'Respirador diseñado para áreas de cuidados críticos neonatales, con soporte respiratorio invasivo y no invasivo incluso durante tiempos prolongados.',
    features: ['Suministro de volumen tidal desde 2 mL', 'Alta sensibilidad de trigger', 'Modos orientados a mecánica respiratoria neonatal', 'Batería con duración mayor a 2.5 horas', 'Almacenamiento de tendencias 72 horas'],
    image: null,
    model3d: null,
  },
  {
    id: 'bomba-infusion-neonatal',
    name: 'Bomba de Infusión Neonatal Precisión Micro',
    brand: 'Kezelmedica',
    area: 'ucin_utip',
    category: 'Infusión',
    description: 'Bomba volumétrica de precisión para dosis extremadamente bajas, diseñada para la administración segura de medicamentos en pacientes neonatales.',
    features: ['Caudal desde 0.1 mL/h', 'Alarma de oclusión sensible', 'Modo microinfusión neonatal', 'Pantalla de fácil lectura', 'Batería de respaldo 6 h'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-neonatal',
    name: 'Monitor Neonatal Anyview P12',
    brand: 'Anyview (Red Beat)',
    area: 'ucin_utip',
    category: 'Monitoreo',
    description: 'Monitor de la Serie P con opciones específicas para atención crítica neonatal, incluyendo detección temprana de cardiopatías congénitas críticas.',
    features: ['Opciones para atención crítica neonatal', 'Evaluación cardiorrespiratoria del neonato', 'SpO2 con tecnología Masimo SET', 'Pantalla 12.1" de alta definición', 'Detección temprana de cardiopatías congénitas'],
    image: '/images/products/anyview-p12.png',
    model3d: null,
  },
  {
    id: 'fototerapia',
    name: 'Fototerapia Neonatal XHZ-90S',
    brand: 'Kezelmedica',
    area: 'ucin_utip',
    category: 'Neonatología',
    description: 'Sistema de fototerapia para el cuidado especializado de recién nacidos con ictericia, con luz azul de alta intensidad conforme a directrices de la Academia Americana de Pediatría.',
    features: ['Luz azul 400–550 nm de alta intensidad', 'Control de intensidad por PWM', 'Pantalla LCD táctil de 4.3"', 'Temporizador integrado', 'Modelo móvil o fijo con brazo de soporte'],
    image: null,
    model3d: null,
  },

  // ─── UCI ──────────────────────────────────────────────────
  {
    id: 'ventilador-mecanico',
    name: 'Ventilador Mecánico Brina',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Ventilación',
    description: 'Solución de ventilación mecánica avanzada y adaptable, pensada para soporte respiratorio desde UCI hasta transporte intrahospitalario.',
    features: ['Modos invasivos y no invasivos', 'Sensor de oxígeno paramagnético (FiO2)', 'Pantalla desmontable y rotativa', 'Batería con duración de 1.5 horas', 'Para adultos, pediátricos y neonatales'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-uci',
    name: 'Plataforma de Monitoreo Root + Radical-7',
    brand: 'Masimo',
    area: 'uci',
    category: 'Monitoreo',
    description: 'Centro de conectividad y monitorización de pacientes que integra múltiples tecnologías Masimo en una sola plataforma, personalizable y escalable.',
    features: ['Co-oximetría de pulso Masimo SET', 'SpHb, SpCO, SpMet y PVi', 'Módulo SedLine para profundidad anestésica (EEG)', 'Oximetría regional O3 cerebral/corporal', 'Hasta 96 horas de tendencias'],
    image: null,
    model3d: null,
  },
  {
    id: 'bomba-jeringa',
    name: 'Bomba de Jeringa Inteligente BJ-Smart',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Infusión',
    description: 'Bomba de jeringa para administración precisa de medicamentos vasoactivos en UCI. Detección automática de jeringa. Sistema anti-bolus.',
    features: ['Caudal 0.1–999 mL/h', 'Anti-bolus al conectar', 'Detección automática jeringa', 'Alarmas oclusión y vacío', 'Comunicación con bomba volumétrica'],
    image: null,
    model3d: null,
  },
  {
    id: 'cama-uci',
    name: 'Cama de UCI Eléctrica CR-500',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Mobiliario Clínico',
    description: 'Cama de UCI eléctrica con función de RCP de un solo movimiento. Pesaje integrado. Balanceo lateral para terapia de prono.',
    features: ['RCP en 1 botón', 'Pesaje integrado ±1 kg', 'Posición prono 30°', 'Altura 35–85 cm', 'Frenos de seguridad x4'],
    image: null,
    model3d: null,
  },
  {
    id: 'capnografo',
    name: 'Analizador de Gases NomoLine ISA AX+',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Monitoreo',
    description: 'Analizador de flujo lateral que mide de forma automatizada y fiable la composición de gases inspiratorios y espiratorios del paciente en UCI.',
    features: ['Mide N2O y CO2 inhalado/exhalado', 'Identifica agentes anestésicos automáticamente', 'Calentamiento en solo 20 segundos', 'Calibración automática de punto cero', 'Configurable como módulo o independiente'],
    image: null,
    model3d: null,
  },
  {
    id: 'desfibrilador-bifasico-2',
    name: 'Desfibrilador Bifásico Cardio-Aid 360-B',
    brand: 'Cardio-Aid',
    area: 'uci',
    category: 'Cardiología',
    description: 'Unidad de desfibrilación bifásica para paro cardiorrespiratorio en UCI, con monitoreo y registro de signos vitales tras la reanimación.',
    features: ['Modo DEA y manual', 'Carga a 200 J en ~2.7 s', 'NIBP SunTech integrado', 'Oximetría de pulso Nellcor', 'Capnografía mainstream y sidestream'],
    image: null,
    model3d: null,
  },

  // ─── IMAGENOLOGÍA ─────────────────────────────────────────
  {
    id: 'rayos-x',
    name: 'Sistema de Rayos X Digital DR-500',
    brand: 'Kezelmedica',
    area: 'imagenologia',
    category: 'Diagnóstico por Imagen',
    description: 'Sistema de rayos X digital directo (DR). Panel detector de 43×43 cm. Adquisición en 4 segundos. Software de procesamiento AI integrado.',
    features: ['Panel 43×43 cm', 'Adquisición 4 s', 'IA para lectura automática', 'DICOM 3.0', 'Dosis reducida 40%'],
    image: null,
    model3d: null,
  },
  {
    id: 'tomografo',
    name: 'Tomógrafo Computarizado 32 Cortes',
    brand: 'Kezelmedica',
    area: 'imagenologia',
    category: 'Diagnóstico por Imagen',
    description: 'Equipo de tomografía computarizada multicorte para estudios de alta resolución con tiempos de adquisición reducidos y baja dosis de radiación.',
    features: ['32 cortes por rotación', 'Reconstrucción multiplanar', 'Protocolos de baja dosis', 'Mesa con capacidad 200 kg', 'Consola de control independiente'],
    image: null,
    model3d: null,
  },
  {
    id: 'ultrasonido',
    name: 'Ultrasonido Diagnóstico General US-E10',
    brand: 'Kezelmedica',
    area: 'imagenologia',
    category: 'Diagnóstico por Imagen',
    description: 'Ultrasonido de alta resolución para diagnóstico general. Elastografía, Doppler color y power Doppler. Pantalla táctil de 21.5".',
    features: ['Elastografía por shear wave', 'Doppler color y power', 'Pantalla 21.5" táctil', 'DICOM/HL7 integrado', 'Sonda lineal/convexa/sectorial'],
    image: null,
    model3d: null,
  },
  {
    id: 'resonancia-magnetica',
    name: 'Resonancia Magnética 1.5T',
    brand: 'Kezelmedica',
    area: 'imagenologia',
    category: 'Diagnóstico por Imagen',
    description: 'Sistema de resonancia magnética de 1.5 Tesla para estudios neurológicos, musculoesqueléticos y de cuerpo completo con alta definición de imagen.',
    features: ['Campo magnético 1.5 Tesla', 'Gantry de diámetro amplio', 'Secuencias rápidas de adquisición', 'Bobinas dedicadas multicanal', 'Compatible con marcapasos condicionales'],
    image: null,
    model3d: null,
  },
  {
    id: 'procesador-imagen',
    name: 'Estación de Trabajo DICOM DiagPro',
    brand: 'Kezelmedica',
    area: 'imagenologia',
    category: 'Diagnóstico por Imagen',
    description: 'Estación de trabajo diagnóstica para procesamiento de imágenes DICOM. Compatible con PACS. Reconstrucción 3D en tiempo real.',
    features: ['Reconstrucción 3D en tiempo real', 'Compatible PACS', 'Monitor doble 4K', 'IA para detección de hallazgos', 'GPU dedicada NVIDIA'],
    image: null,
    model3d: null,
  },

  // ─── HOSPITALIZACIÓN ──────────────────────────────────────
  {
    id: 'cama-hospitalaria',
    name: 'Cama Hospitalaria Estándar CH-200',
    brand: 'Kezelmedica',
    area: 'hospitalizacion',
    category: 'Mobiliario Clínico',
    description: 'Cama hospitalaria manual de 2 funciones con barandales rebatibles de 3 secciones. Ruedas de 15 cm con freno central.',
    features: ['2 funciones manuales', 'Barandales 3 secciones', 'Ruedas 15 cm con freno', 'Colchón 10 cm', 'Soporte suero integrado'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-signos',
    name: 'Monitor de Paciente Anyview P15',
    brand: 'Anyview (Red Beat)',
    area: 'hospitalizacion',
    category: 'Monitoreo',
    description: 'Monitor de la Serie P diseñado para áreas de emergencia y hospitalización general, con almacenamiento extendido de tendencias del paciente.',
    features: ['Pantalla 15.6"', 'Hasta 1,800 horas de tendencias', 'Función Sepsis View para detección temprana', 'Asistente de RCP integrado', 'Interfaz intuitiva y eficiente'],
    image: null,
    model3d: null,
  },
  {
    id: 'bomba-iv',
    name: 'Bomba Volumétrica Inteligente BV-Pro',
    brand: 'Kezelmedica',
    area: 'hospitalizacion',
    category: 'Infusión',
    description: 'Bomba de infusión volumétrica con biblioteca de medicamentos preprogramada. Sistema anticaída de flujo. Alarmas inteligentes.',
    features: ['Biblioteca 500 medicamentos', 'Caudal 1–999 mL/h', 'Alarma anticaída', 'Pantalla táctil a color', 'Compatible con bomba de jeringa'],
    image: null,
    model3d: null,
  },
  {
    id: 'riel-suero',
    name: 'Riel Porta Suero de Techo',
    brand: 'Kezelmedica',
    area: 'hospitalizacion',
    category: 'Mobiliario Clínico',
    description: 'Sistema de riel para soportes de suero montado en techo, permite reposicionar bombas de infusión sin obstruir el paso alrededor de la cama.',
    features: ['Montaje empotrado en techo', 'Recorrido deslizante suave', 'Capacidad 4 líneas de infusión', 'Acabado en acero inoxidable', 'Sin obstrucción de piso'],
    image: null,
    model3d: null,
  },
  {
    id: 'cama-electrica',
    name: 'Cama Hospitalaria Eléctrica de 3 Funciones',
    brand: 'Kezelmedica',
    area: 'hospitalizacion',
    category: 'Mobiliario Clínico',
    description: 'Cama eléctrica de hospitalización general con ajuste de altura, respaldo y rodillas mediante control de paciente integrado.',
    features: ['3 funciones eléctricas', 'Control de paciente integrado', 'Barandales abatibles', 'Altura 40–80 cm', 'Ruedas con freno central'],
    image: null,
    model3d: null,
  },

  // ─── HEMODIÁLISIS ─────────────────────────────────────────
  {
    id: 'maquina-hemodialisis',
    name: 'Máquina de Hemodiálisis HD-Pro 5000',
    brand: 'Kezelmedica',
    area: 'hemodialisis',
    category: 'Hemodiálisis',
    description: 'Sistema de hemodiálisis de alta eficiencia con ultrafiltración controlada. Online HDF, HD y SLED. Pantalla táctil de 15". Desinfección automática.',
    features: ['HD, HDF online, SLED', 'Ultrafiltración ±5 mL/h', 'Pantalla táctil 15"', 'Desinfección automática', 'Conectividad remota'],
    image: null,
    model3d: null,
  },
  {
    id: 'sillon-reclinable',
    name: 'Sillón Reclinable para Hemodiálisis',
    brand: 'Kezelmedica',
    area: 'hemodialisis',
    category: 'Mobiliario Clínico',
    description: 'Sillón clínico reclinable eléctrico para sesiones de hemodiálisis prolongadas, con tapicería antibacterial y ajuste independiente de respaldo y piernas.',
    features: ['Reclinado eléctrico independiente', 'Tapicería antibacterial lavable', 'Apoyabrazos abatibles', 'Ruedas con freno', 'Capacidad 180 kg'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-hemo',
    name: 'Monitor de Signos Vitales para Hemodiálisis',
    brand: 'Kezelmedica',
    area: 'hemodialisis',
    category: 'Monitoreo',
    description: 'Monitor compacto para seguimiento de presión arterial y frecuencia cardiaca del paciente durante sesiones de diálisis.',
    features: ['Medición automática por intervalos', 'Pantalla de fácil lectura', 'Alarmas configurables', 'Montaje en sillón o rodable', 'Batería de respaldo'],
    image: null,
    model3d: null,
  },
  {
    id: 'purificador-agua',
    name: 'Purificador de Agua para Hemodiálisis PW-HD',
    brand: 'Kezelmedica',
    area: 'hemodialisis',
    category: 'Hemodiálisis',
    description: 'Sistema de purificación de agua de ósmosis inversa doble paso para hemodiálisis. Cumple normativa AAMI TIR13. Producción 600 L/h.',
    features: ['Osmosis inversa doble paso', '600 L/h de producción', 'Cumple AAMI TIR13', 'Monitoreo conductividad 24/7', 'Alarma de contaminación'],
    image: null,
    model3d: null,
  },

  // ─── TELEMEDICINA ─────────────────────────────────────────
  {
    id: 'estacion-telemedicina',
    name: 'Estación de Telemedicina TeleMed-Pro',
    brand: 'Kezelmedica',
    area: 'telemedicina',
    category: 'Telemedicina',
    description: 'Carrito de telemedicina todo en uno. Cámara PTZ 4K, monitor dual, periféricos diagnósticos integrados. Videoconsulta cifrada HIPAA.',
    features: ['Cámara PTZ 4K', 'Monitor dual 24"', 'Dermatoscopio y otoscopio digital', 'Videoconsulta HIPAA', 'Batería 8 h'],
    image: null,
    model3d: null,
  },
  {
    id: 'camara-hd',
    name: 'Videotoscopio Aurical Otocam 300',
    brand: 'Aurical',
    area: 'telemedicina',
    category: 'Telemedicina',
    description: 'Solución avanzada para exploración otológica remota, diseñada para captura, análisis y almacenamiento de imágenes y video en consultas de telemedicina.',
    features: ['Captura de imagen y video en alta resolución', 'Cable de 2.7 m de libertad de movimiento', 'Compatible con Aurical Freefit y Otosuite', 'Botones independientes oído izq/der', 'Formato compacto y portátil'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-diagnostico',
    name: 'Monitor Diagnóstico para Videoconsulta',
    brand: 'Kezelmedica',
    area: 'telemedicina',
    category: 'Telemedicina',
    description: 'Monitor médico de alta definición para visualización de estudios y videoconsulta en tiempo real con especialistas remotos.',
    features: ['Pantalla médica 24" Full HD', 'Calibración de color certificada', 'Entradas HDMI/DisplayPort', 'Soporte articulado ajustable', 'Modo bajo consumo'],
    image: null,
    model3d: null,
  },
  {
    id: 'estetoscopio-digital',
    name: 'Estetoscopio Digital Inalámbrico ED-3',
    brand: 'Kezelmedica',
    area: 'telemedicina',
    category: 'Telemedicina',
    description: 'Estetoscopio electrónico con transmisión Bluetooth. Amplificación 40× sobre acústico. Compatible con plataformas de telemedicina.',
    features: ['Amplificación 40×', 'Bluetooth 5.0', 'Filtra ruido ambiental', 'Graba y comparte', 'Compatible iOS/Android/PC'],
    image: null,
    model3d: null,
  },

  // ─── CONCEPCIÓN & GESTIÓN ─────────────────────────────────
  {
    id: 'estacion-trabajo',
    name: 'Estación de Trabajo Clínico WorkMed',
    brand: 'Kezelmedica',
    area: 'concepcion',
    category: 'Gestión Hospitalaria',
    description: 'Estación de trabajo móvil para gestión hospitalaria. Monitor integrado, escáner de código de barras y lector RFID. Batería de larga duración.',
    features: ['Monitor 15" integrado', 'Lector RFID/código de barras', 'Batería 12 h', 'Soporte medicación segura', 'Software compatible HIS'],
    image: null,
    model3d: null,
  },
  {
    id: 'mobiliario-clinico',
    name: 'Mobiliario Clínico Modular',
    brand: 'Kezelmedica',
    area: 'concepcion',
    category: 'Gestión Hospitalaria',
    description: 'Conjunto de mobiliario modular para oficinas de gestión y proyectos hospitalarios: escritorios, gabinetes y estaciones de reunión.',
    features: ['Módulos reconfigurables', 'Superficies antibacteriales', 'Gabinetes con cierre', 'Cableado integrado', 'Acabados anticorrosivos'],
    image: null,
    model3d: null,
  },
  {
    id: 'pantalla-presentacion',
    name: 'Pantalla Interactiva de Presentación',
    brand: 'Kezelmedica',
    area: 'concepcion',
    category: 'Gestión Hospitalaria',
    description: 'Pantalla táctil interactiva para presentación de proyectos, planos y reportes en reuniones de gestión hospitalaria.',
    features: ['Pantalla táctil 65"', 'Conectividad inalámbrica', 'Compatible con videoconferencia', 'Anotación digital en tiempo real', 'Montaje de piso o pared'],
    image: null,
    model3d: null,
  },
];

// Índice por ID para búsqueda rápida
export const EQUIPMENT_BY_ID = Object.fromEntries(
  EQUIPMENT_DATA.map(e => [e.id, e])
);

// Índice por área
export const EQUIPMENT_BY_AREA = EQUIPMENT_DATA.reduce((acc, eq) => {
  if (!acc[eq.area]) acc[eq.area] = [];
  acc[eq.area].push(eq);
  return acc;
}, {});
