// ============================================================
// BASE DE DATOS DE EQUIPOS MÉDICOS — Kezelmedica
// ~55 equipos distribuidos en las 15 áreas
// ============================================================

export const EQUIPMENT_DATA = [
  // ─── TRANSPORTE / AMBULANCIA ──────────────────────────────
  {
    id: 'camilla-transporte',
    name: 'Camilla de Transporte Plegable',
    brand: 'Kezelmedica',
    area: 'ambulancia',
    category: 'Transporte',
    description: 'Camilla de aluminio de alta resistencia con sistema de plegado rápido. Soporta hasta 250 kg. Ruedas omnidireccionales con freno.',
    features: ['Capacidad 250 kg', 'Plegado en 3 segundos', 'Ruedas de 15 cm con freno', 'Barandales abatibles', 'Compatible con helicóptero'],
    image: null,
    model3d: null,
  },
  {
    id: 'desfibrilador-portatil',
    name: 'Desfibrilador Portátil DAE Pro',
    brand: 'Kezelmedica',
    area: 'ambulancia',
    category: 'Cardiología',
    description: 'Desfibrilador automático externo de última generación. Instrucciones de voz en español. Ideal para primeros respondientes y traslados.',
    features: ['DAE totalmente automático', 'Voz en español e inglés', 'Batería 5 años en standby', 'Resistente a agua IP55', 'ECG integrado 12 derivaciones'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-transporte',
    name: 'Monitor de Transporte Multiparamétrico',
    brand: 'Kezelmedica',
    area: 'ambulancia',
    category: 'Monitoreo',
    description: 'Monitor compacto para transporte de pacientes críticos. Pantalla de 10" táctil. Batería de larga duración para traslados prolongados.',
    features: ['Pantalla táctil 10"', 'ECG, SpO2, NIBP, Temp', 'Batería 8 horas', 'Alarmas configurables', 'Registro de datos en nube'],
    image: null,
    model3d: null,
  },
  {
    id: 'mochila-trauma',
    name: 'Mochila de Trauma Profesional',
    brand: 'Kezelmedica',
    area: 'ambulancia',
    category: 'Emergencias',
    description: 'Mochila de respuesta rápida con compartimentos organizados para medicamentos, equipos de vía aérea y signos vitales. Material impermeable.',
    features: ['Compartimentos codificados por color', 'Material Nylon 1000D', '35L de capacidad', 'Incluye torniquete y compresses', 'Compatible MOLLE'],
    image: null,
    model3d: null,
  },

  // ─── URGENCIAS ────────────────────────────────────────────
  {
    id: 'camilla-urgencias',
    name: 'Camilla de Urgencias Eléctrica',
    brand: 'Kezelmedica',
    area: 'urgencias',
    category: 'Mobiliario Clínico',
    description: 'Camilla eléctrica de urgencias con ajuste de altura motorizado y respaldo. Superficies antibacteriales. Barandales de seguridad de 3 secciones.',
    features: ['Altura 55–95 cm motorizada', 'Posición Trendelenburg', 'Colchón 10 cm viscoelástico', 'Soporte suero integrado', 'Frenos centralizados'],
    image: null,
    model3d: null,
  },
  {
    id: 'carro-rojo',
    name: 'Carro Rojo de Reanimación',
    brand: 'Kezelmedica',
    area: 'urgencias',
    category: 'Emergencias',
    description: 'Carro de reanimación completo con desfibrilador integrado. Cajones con sistema de seguridad. Totalmente equipado para paros cardiorrespiratorios.',
    features: ['5 cajones con llave', 'Superficie de RCP', 'Porta suero y oxígeno', 'Incluye desfibrilador DAE', 'Ruedas de 15 cm silenciosas'],
    image: null,
    model3d: null,
  },
  {
    id: 'desfibrilador-bifasico',
    name: 'Desfibrilador Bifásico Manual DF-360',
    brand: 'Kezelmedica',
    area: 'urgencias',
    category: 'Cardiología',
    description: 'Desfibrilador bifásico profesional para uso en urgencias hospitalarias. Monitoreo ECG integrado, marcapaso transcutáneo y cardioversión sincronizada.',
    features: ['Tecnología bifásica truncada', 'Marcapaso transcutáneo', 'Cardioversión sincronizada', 'Pantalla color 12" táctil', 'Memoria 1000 eventos'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-vital',
    name: 'Monitor Multiparamétrico MV-15',
    brand: 'Kezelmedica',
    area: 'urgencias',
    category: 'Monitoreo',
    description: 'Monitor de signos vitales de alta resolución para áreas de urgencias. 12 derivaciones ECG, capnografía integrada y análisis de arritmias.',
    features: ['Pantalla 15" TFT táctil', 'ECG 12 derivaciones', 'Capnografía EtCO2', 'SpO2 Masimo SET', 'Conectividad WiFi/HL7'],
    image: null,
    model3d: null,
  },
  {
    id: 'aspirador-portatil',
    name: 'Aspirador de Secreciones Portátil',
    brand: 'Kezelmedica',
    area: 'urgencias',
    category: 'Vía Aérea',
    description: 'Aspirador de secreciones de alto flujo para manejo de vía aérea en urgencias. Operación con batería recargable y corriente alterna.',
    features: ['Flujo 30 L/min', 'Vacío -80 kPa', 'Batería 45 min', 'Depósito 500 mL reutilizable', 'Silencioso < 68 dB'],
    image: null,
    model3d: null,
  },

  // ─── QUIRÓFANO ────────────────────────────────────────────
  {
    id: 'mesa-quirurgica',
    name: 'Mesa Quirúrgica Motorizada QX-500',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Mobiliario Quirúrgico',
    description: 'Mesa quirúrgica eléctrica de última generación. Control remoto inalámbrico. Múltiples posiciones para todo tipo de cirugías. Tapa radiotransparente.',
    features: ['Control remoto inalámbrico', 'Altura 65–115 cm', 'Inclinación ±30°', 'Tapa radiotransparente', 'Capacidad 320 kg'],
    image: null,
    model3d: null,
  },
  {
    id: 'lampara-cielitica',
    name: 'Lámpara Cielítica LED Doble',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Iluminación Quirúrgica',
    description: 'Lámpara quirúrgica LED de doble cabezal con 160,000 lux de iluminación. Sin sombras, sin calor. Temperatura de color ajustable 3,500–5,000 K.',
    features: ['160,000 lux', 'Temperatura color 3500–5000 K', 'Sin sombras', 'Vida LED 50,000 h', 'Cabezal estéril esterilizable'],
    image: null,
    model3d: null,
  },
  {
    id: 'torre-laparoscopia',
    name: 'Torre de Laparoscopia 4K',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Cirugía Mínimamente Invasiva',
    description: 'Sistema de laparoscopia con cámara 4K Ultra HD. Fuente de luz LED de 300W. Monitor de 31.5" 4K. Compatible con instrumental Karl Storz y Olympus.',
    features: ['Cámara 4K Ultra HD', 'Monitor 31.5" 4K', 'Luz LED 300 W', 'Grabación en USB/red', 'Compatible con principales marcas'],
    image: null,
    model3d: null,
  },
  {
    id: 'maquina-anestesia',
    name: 'Máquina de Anestesia Workstation AN-7',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Anestesiología',
    description: 'Estación de trabajo de anestesia con ventilación integrada. Monitor de agentes anestésicos. Pantalla táctil de 15". Compatible con todos los agentes halogenados.',
    features: ['Ventilador integrado', 'Monitor de gases', 'Pantalla táctil 15"', 'VCV, PCV, PSV', 'Batería de respaldo 4 h'],
    image: null,
    model3d: null,
  },
  {
    id: 'electrocauterio',
    name: 'Electrobisturí de Alta Frecuencia EB-400',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Electrocirugia',
    description: 'Electrobisturí de 400W con corte y coagulación monopolar/bipolar. Sistema de autochequeo. Compatible con argón para cirugía hepatobiliar.',
    features: ['400W potencia', 'Mono y bipolar', 'Compatible argón', 'Modo automático REM', 'Pantalla táctil 7"'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-qx',
    name: 'Monitor de Quirófano Integrado',
    brand: 'Kezelmedica',
    area: 'quirofano',
    category: 'Monitoreo',
    description: 'Monitor anestésico completo para quirófano. Monitoreo hemodinámico invasivo y no invasivo. Índice biespectral (BIS) integrado.',
    features: ['BIS integrado', 'PIC invasiva', 'Gasto cardíaco', 'Pantalla 19"', 'Alarmas sonoras y visuales'],
    image: null,
    model3d: null,
  },

  // ─── TERAPIA INTERMEDIA ───────────────────────────────────
  {
    id: 'cama-electrica-ti',
    name: 'Cama Eléctrica Hospitalaria TI-900',
    brand: 'Kezelmedica',
    area: 'terapia_intermedia',
    category: 'Mobiliario Clínico',
    description: 'Cama hospitalaria eléctrica de 4 funciones para terapia intermedia. Rieles laterales abatibles. Colchón antiescaras opcional.',
    features: ['4 funciones eléctricas', 'Altura 35–80 cm', 'Posición Fowler y Trendelenburg', 'Frenos pediátricos', 'Compatible radiología'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-multiparametrico',
    name: 'Monitor Multiparamétrico MP-12',
    brand: 'Kezelmedica',
    area: 'terapia_intermedia',
    category: 'Monitoreo',
    description: 'Monitor de signos vitales para terapia intermedia. Pantalla de 12.1" táctil. Conectividad a central de monitoreo.',
    features: ['ECG 5 derivaciones', 'SpO2, NIBP, Temperatura', 'Pantalla 12.1" táctil', 'Central de monitoreo WiFi', 'Alarmas inteligentes'],
    image: null,
    model3d: null,
  },
  {
    id: 'oximetro',
    name: 'Oxímetro de Pulso Masimo Rad-97',
    brand: 'Kezelmedica',
    area: 'terapia_intermedia',
    category: 'Monitoreo',
    description: 'Oxímetro de pulso de precisión con tecnología Masimo SET. Resistente a movimiento y baja perfusión. Pantalla a color.',
    features: ['Tecnología Masimo SET', 'SpO2 y SpMet', 'Resistente a movimiento', 'Alarmas configurables', 'Memoria 72 horas'],
    image: null,
    model3d: null,
  },
  {
    id: 'ventilador-ti',
    name: 'Ventilador de Terapia Intermedia VT-200',
    brand: 'Kezelmedica',
    area: 'terapia_intermedia',
    category: 'Ventilación',
    description: 'Ventilador invasivo/no invasivo para terapia intermedia. Modos VCV, PCV, CPAP, BiPAP. Pantalla gráfica de curvas de flujo y presión.',
    features: ['VCV, PCV, CPAP, BiPAP', 'Mascarilla o tubo endotraqueal', 'Alarmas multinivel', 'Pantalla gráfica color', 'Nebulizador integrado'],
    image: null,
    model3d: null,
  },

  // ─── ENDOSCOPIA ───────────────────────────────────────────
  {
    id: 'torre-endoscopia',
    name: 'Torre de Endoscopia Full HD',
    brand: 'Kezelmedica',
    area: 'endoscopia',
    category: 'Endoscopia',
    description: 'Sistema de endoscopia completo con procesador de video Full HD. Monitor de 27". Fuente de luz LED integrada. Compatible con instrumental flexible.',
    features: ['Procesador HD 1080p', 'Monitor 27" Full HD', 'LED 250 W', 'Grabación USB/DICOM', 'Compatible Olympus/Pentax'],
    image: null,
    model3d: null,
  },
  {
    id: 'gastroscopio',
    name: 'Gastroscopio Flexible GF-H290',
    brand: 'Kezelmedica',
    area: 'endoscopia',
    category: 'Endoscopia',
    description: 'Gastroscopio de última generación para diagnóstico y terapéutica gástrica. Canal de trabajo de 3.7 mm. Ángulo de visión 140°.',
    features: ['Ángulo de visión 140°', 'Canal de trabajo 3.7 mm', 'Longitud 103 cm', 'Punta angulable 210°', 'Resistente a autoclave'],
    image: null,
    model3d: null,
  },
  {
    id: 'colonoscopio',
    name: 'Colonoscopio CF-H290',
    brand: 'Kezelmedica',
    area: 'endoscopia',
    category: 'Endoscopia',
    description: 'Colonoscopio de alta definición con sistema de inserción variable. Longitud de 168 cm. Canal de trabajo de 3.7 mm para polipectomía.',
    features: ['Longitud 168 cm', 'Canal 3.7 mm', 'Inserción variable', 'Ángulo visión 170°', 'Compatible NBI (narrow band)'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-hd-endo',
    name: 'Monitor Endoscopia 4K 32"',
    brand: 'Kezelmedica',
    area: 'endoscopia',
    category: 'Imágenes',
    description: 'Monitor médico 4K de 32 pulgadas diseñado para endoscopia. Reproducción exacta de color. Baja latencia. Certificado médico.',
    features: ['4K Ultra HD', '32 pulgadas', 'Latencia < 20 ms', 'Certificado IEC 60601', 'Soporte HDMI y SDI'],
    image: null,
    model3d: null,
  },

  // ─── SUMINISTRO DE GAS ────────────────────────────────────
  {
    id: 'tanque-oxigeno',
    name: 'Tanque de Oxígeno Medicinal 10m³',
    brand: 'Kezelmedica',
    area: 'suministro_gas',
    category: 'Gases Médicos',
    description: 'Tanque de almacenamiento de oxígeno medicinal de alta presión. Válvula de seguridad integrada. Certificado por COFEPRIS.',
    features: ['Capacidad 10 m³', 'Presión máx 200 bar', 'Válvula de seguridad', 'Certificado COFEPRIS', 'Acero inoxidable 316L'],
    image: null,
    model3d: null,
  },
  {
    id: 'regulador-presion',
    name: 'Regulador de Presión de Gas RP-50',
    brand: 'Kezelmedica',
    area: 'suministro_gas',
    category: 'Gases Médicos',
    description: 'Regulador de presión de dos etapas para oxígeno, N2O y aire medicinal. Caudal ajustable de 0–15 L/min.',
    features: ['Dos etapas de regulación', 'Caudal 0–15 L/min', 'Manómetro integrado', 'Conector DISS', 'Compatible todos los gases médicos'],
    image: null,
    model3d: null,
  },
  {
    id: 'manifold-gas',
    name: 'Manifold de Gases Médicos',
    brand: 'Kezelmedica',
    area: 'suministro_gas',
    category: 'Gases Médicos',
    description: 'Panel de distribución de gases médicos con capacidad para 12 cilindros. Conmutación automática entre bancadas.',
    features: ['12 cilindros por bancada', 'Cambio automático', 'Alarma de presión baja', 'Cabezas DISS', 'Aprobado NOM-090'],
    image: null,
    model3d: null,
  },

  // ─── TOCO CIRUGÍA ─────────────────────────────────────────
  {
    id: 'mesa-parto',
    name: 'Mesa de Parto Eléctrica MP-300',
    brand: 'Kezelmedica',
    area: 'toco_cirugia',
    category: 'Obstetricia',
    description: 'Mesa de parto eléctrica con 6 posiciones. Segmento de pierna desmontable. Tapicería antibacterial. Accesorios de quirófano incluidos.',
    features: ['6 posiciones eléctricas', 'Segmento pierna desmontable', 'Altura 62–100 cm', 'Tapicería antibacterial', 'Capacidad 300 kg'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-fetal',
    name: 'Monitor Fetal Electrónico MF-800',
    brand: 'Kezelmedica',
    area: 'toco_cirugia',
    category: 'Obstetricia',
    description: 'Monitor fetal electrónico con cardiotocografía (CTG). Detección de gemelos. Pantalla táctil. Impresora térmica integrada. Conectividad WiFi.',
    features: ['Detección de gemelos', 'Pantalla táctil 10"', 'Impresora térmica integrada', 'WiFi para central', 'Alarmas de FCF'],
    image: null,
    model3d: null,
  },
  {
    id: 'incubadora-neonatal',
    name: 'Incubadora Neonatal de Transporte IT-80',
    brand: 'Kezelmedica',
    area: 'toco_cirugia',
    category: 'Neonatología',
    description: 'Incubadora de transporte para neonatos con sistema de calefacción independiente. Batería de 8 horas. Compatible con ventiladores y monitores portátiles.',
    features: ['Temperatura 34–37°C ±0.1°C', 'Batería 8 horas', 'Humedad controlada', 'Peso < 15 kg', 'Compatible respiradores portátiles'],
    image: null,
    model3d: null,
  },

  // ─── UCIN / UTIP ──────────────────────────────────────────
  {
    id: 'incubadora-neonatal-2',
    name: 'Incubadora Neonatal Fija IN-2000',
    brand: 'Kezelmedica',
    area: 'ucin_utip',
    category: 'Neonatología',
    description: 'Incubadora neonatal de cuidado intensivo con doble pared. Control preciso de temperatura y humedad. Alarmas de desconexión y temperatura.',
    features: ['Doble pared aislante', 'Humedad 30–95%', 'Control servo de piel', 'Acceso de 4 portillas', 'Báscula integrada'],
    image: null,
    model3d: null,
  },
  {
    id: 'ventilador-neonatal',
    name: 'Ventilador Neonatal VN-High',
    brand: 'Kezelmedica',
    area: 'ucin_utip',
    category: 'Ventilación',
    description: 'Ventilador neonatal de alta frecuencia. Modos HFO, SIMV, CPAP. Volumen garantizado. Monitoreo de mecánica pulmonar en tiempo real.',
    features: ['Alta frecuencia HFO', 'Volumen garantizado', 'SIMV, CPAP, NAVA', 'Monitoreo mecánica pulmonar', 'Humidificador integrado'],
    image: null,
    model3d: null,
  },
  {
    id: 'fototerapia',
    name: 'Unidad de Fototerapia LED FT-Pro',
    brand: 'Kezelmedica',
    area: 'ucin_utip',
    category: 'Neonatología',
    description: 'Unidad de fototerapia LED de alto rendimiento para tratamiento de hiperbilirrubinemia neonatal. Irradiancia superior a 35 μW/cm²/nm.',
    features: ['LED azul 460 nm', 'Irradiancia > 35 μW/cm²/nm', 'Sin calor ni UV', 'Vida LED 20,000 h', 'Timer programable'],
    image: null,
    model3d: null,
  },

  // ─── UCI ──────────────────────────────────────────────────
  {
    id: 'ventilador-mecanico',
    name: 'Ventilador Mecánico V-Pro 600',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Ventilación',
    description: 'Ventilador de cuidados intensivos de última generación. Más de 15 modos ventilatorios. Curvas de flujo, presión y volumen en tiempo real. Tecnología NAVA.',
    features: ['15+ modos ventilatorios', 'Tecnología NAVA/PAV+', 'Pantalla gráfica 15"', 'Humidificador integrado', 'Alarmas multinivel'],
    image: null,
    model3d: null,
  },
  {
    id: 'monitor-uci',
    name: 'Monitor UCI Completo MC-Pro',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Monitoreo',
    description: 'Monitor de UCI de alta complejidad con monitoreo hemodinámico invasivo, capnografía, BIS, temperatura y SpO2 Masimo. Central de enfermería integrada.',
    features: ['Línea arterial invasiva', 'PVC y PAP', 'BIS neurológico', 'EtCO2 capnografía', 'Central de monitoreo'],
    image: null,
    model3d: null,
  },
  {
    id: 'bomba-jeringa',
    name: 'Bomba de Jeringa Inteligente BJ-Smart',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Infusión',
    description: 'Bomba de jeringa para administración precisa de medicamentos vasoactivos en UCI. Detección automática de jeringa. Sistema anti-bolus.',
    features: ['Caudal 0.1–999 mL/h', 'Anti-bolus al conectar', 'Detección automática jeringa', 'Alarmas oclusión y vacío', 'Comunicación con bomba volumétrica'],
    image: null,
    model3d: null,
  },
  {
    id: 'cama-uci',
    name: 'Cama de UCI Eléctrica CR-500',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Mobiliario Clínico',
    description: 'Cama de UCI eléctrica con función de RCP de un solo movimiento. Pesaje integrado. Balanceo lateral para terapia de prono.',
    features: ['RCP en 1 botón', 'Pesaje integrado ±1 kg', 'Posición prono 30°', 'Altura 35–85 cm', 'Frenos de seguridad x4'],
    image: null,
    model3d: null,
  },
  {
    id: 'capnografo',
    name: 'Capnógrafo Portátil CO2 CAP-200',
    brand: 'Kezelmedica',
    area: 'uci',
    category: 'Monitoreo',
    description: 'Capnógrafo mainstream para monitoreo continuo de CO2 al final de la espiración. Pantalla gráfica. Alarmas de apnea.',
    features: ['Mainstream o sidestream', 'EtCO2 y FiCO2', 'Alarma de apnea', 'Pantalla gráfica', 'Compatible intubado y no intubado'],
    image: null,
    model3d: null,
  },

  // ─── IMAGENOLOGÍA ─────────────────────────────────────────
  {
    id: 'rayos-x',
    name: 'Sistema de Rayos X Digital DR-500',
    brand: 'Kezelmedica',
    area: 'imagenologia',
    category: 'Diagnóstico por Imagen',
    description: 'Sistema de rayos X digital directo (DR). Panel detector de 43×43 cm. Adquisición en 4 segundos. Software de procesamiento AI integrado.',
    features: ['Panel 43×43 cm', 'Adquisición 4 s', 'IA para lectura automática', 'DICOM 3.0', 'Dosis reducida 40%'],
    image: null,
    model3d: null,
  },
  {
    id: 'ultrasonido',
    name: 'Ultrasonido Diagnóstico General US-E10',
    brand: 'Kezelmedica',
    area: 'imagenologia',
    category: 'Diagnóstico por Imagen',
    description: 'Ultrasonido de alta resolución para diagnóstico general. Elastografía, Doppler color y power Doppler. Pantalla táctil de 21.5".',
    features: ['Elastografía por shear wave', 'Doppler color y power', 'Pantalla 21.5" táctil', 'DICOM/HL7 integrado', 'Sonda lineal/convexa/sectorial'],
    image: null,
    model3d: null,
  },
  {
    id: 'procesador-imagen',
    name: 'Estación de Trabajo DICOM DiagPro',
    brand: 'Kezelmedica',
    area: 'imagenologia',
    category: 'Diagnóstico por Imagen',
    description: 'Estación de trabajo diagnóstica para procesamiento de imágenes DICOM. Compatible con PACS. Reconstrucción 3D en tiempo real.',
    features: ['Reconstrucción 3D en tiempo real', 'Compatible PACS', 'Monitor doble 4K', 'IA para detección de hallazgos', 'GPU dedicada NVIDIA'],
    image: null,
    model3d: null,
  },

  // ─── HOSPITALIZACIÓN ──────────────────────────────────────
  {
    id: 'cama-hospitalaria',
    name: 'Cama Hospitalaria Estándar CH-200',
    brand: 'Kezelmedica',
    area: 'hospitalizacion',
    category: 'Mobiliario Clínico',
    description: 'Cama hospitalaria manual de 2 funciones con barandales rebatibles de 3 secciones. Ruedas de 15 cm con freno central.',
    features: ['2 funciones manuales', 'Barandales 3 secciones', 'Ruedas 15 cm con freno', 'Colchón 10 cm', 'Soporte suero integrado'],
    image: null,
    model3d: null,
  },
  {
    id: 'bomba-iv',
    name: 'Bomba Volumétrica Inteligente BV-Pro',
    brand: 'Kezelmedica',
    area: 'hospitalizacion',
    category: 'Infusión',
    description: 'Bomba de infusión volumétrica con biblioteca de medicamentos preprogramada. Sistema anticaída de flujo. Alarmas inteligentes.',
    features: ['Biblioteca 500 medicamentos', 'Caudal 1–999 mL/h', 'Alarma anticaída', 'Pantalla táctil a color', 'Compatible con bomba de jeringa'],
    image: null,
    model3d: null,
  },

  // ─── HEMODIÁLISIS ─────────────────────────────────────────
  {
    id: 'maquina-hemodialisis',
    name: 'Máquina de Hemodiálisis HD-Pro 5000',
    brand: 'Kezelmedica',
    area: 'hemodialisis',
    category: 'Hemodiálisis',
    description: 'Sistema de hemodiálisis de alta eficiencia con ultrafiltración controlada. Online HDF, HD y SLED. Pantalla táctil de 15". Desinfección automática.',
    features: ['HD, HDF online, SLED', 'Ultrafiltración ±5 mL/h', 'Pantalla táctil 15"', 'Desinfección automática', 'Conectividad remota'],
    image: null,
    model3d: null,
  },
  {
    id: 'purificador-agua',
    name: 'Purificador de Agua para Hemodiálisis PW-HD',
    brand: 'Kezelmedica',
    area: 'hemodialisis',
    category: 'Hemodiálisis',
    description: 'Sistema de purificación de agua de ósmosis inversa doble paso para hemodiálisis. Cumple normativa AAMI TIR13. Producción 600 L/h.',
    features: ['Osmosis inversa doble paso', '600 L/h de producción', 'Cumple AAMI TIR13', 'Monitoreo conductividad 24/7', 'Alarma de contaminación'],
    image: null,
    model3d: null,
  },

  // ─── TELEMEDICINA ─────────────────────────────────────────
  {
    id: 'estacion-telemedicina',
    name: 'Estación de Telemedicina TeleMed-Pro',
    brand: 'Kezelmedica',
    area: 'telemedicina',
    category: 'Telemedicina',
    description: 'Carrito de telemedicina todo en uno. Cámara PTZ 4K, monitor dual, periféricos diagnósticos integrados. Videoconsulta cifrada HIPAA.',
    features: ['Cámara PTZ 4K', 'Monitor dual 24"', 'Dermatoscopio y otoscopio digital', 'Videoconsulta HIPAA', 'Batería 8 h'],
    image: null,
    model3d: null,
  },
  {
    id: 'estetoscopio-digital',
    name: 'Estetoscopio Digital Inalámbrico ED-3',
    brand: 'Kezelmedica',
    area: 'telemedicina',
    category: 'Telemedicina',
    description: 'Estetoscopio electrónico de 3M Littmann con transmisión Bluetooth. Amplificación 40× sobre acústico. Compatible con plataformas de telemedicina.',
    features: ['Amplificación 40×', 'Bluetooth 5.0', 'Filtra ruido ambiental', 'Graba y comparte', 'Compatible iOS/Android/PC'],
    image: null,
    model3d: null,
  },

  // ─── CONCEPCIÓN & GESTIÓN ─────────────────────────────────
  {
    id: 'estacion-trabajo',
    name: 'Estación de Trabajo Clínico WorkMed',
    brand: 'Kezelmedica',
    area: 'concepcion',
    category: 'Gestión Hospitalaria',
    description: 'Estación de trabajo móvil para gestión hospitalaria. Monitor integrado, escáner de código de barras y lector RFID. Batería de larga duración.',
    features: ['Monitor 15" integrado', 'Lector RFID/código de barras', 'Batería 12 h', 'Soporte medicación segura', 'Software compatible HIS'],
    image: null,
    model3d: null,
  },
];

// Índice por ID para búsqueda rápida
export const EQUIPMENT_BY_ID = Object.fromEntries(
  EQUIPMENT_DATA.map(e => [e.id, e])
);

// Índice por área
export const EQUIPMENT_BY_AREA = EQUIPMENT_DATA.reduce((acc, eq) => {
  if (!acc[eq.area]) acc[eq.area] = [];
  acc[eq.area].push(eq);
  return acc;
}, {});
