import { AREA_IDS, FLOOR_Y, COLORS } from '../utils/constants.js';

// ============================================================
// DEFINICIÓN DE LAS 15 ÁREAS DEL HOSPITAL
// Cada área tiene: id, nombre, piso, posición central (x,z),
// dimensiones (w,d), color de acento, y equipos asociados.
// ============================================================

// Escala del hospital: cada "celda" del grid = 8 unidades Three.js
const S = 8;   // escala base de sala
const C = 3;   // ancho de corredor

export const AREA_DEFINITIONS = [
  // ─── PLANTA BAJA ─────────────────────────────────────────
  {
    id: AREA_IDS.LOBBY,
    name: 'Lobby / Recepción',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    // Centro del lobby — punto de spawn del jugador
    cx: 0, cz: 0,
    w: C * 2, d: C * 2,
    color: COLORS.KEZEL_BLUE,
    accentColor: '#0055A4',
    equipmentIds: [],
    isSpawn: true,
    spawnX: 0, spawnZ: 2,
  },
  {
    id: AREA_IDS.AMBULANCIA,
    name: 'Transporte / Ambulancia',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    cx: -3 * S, cz: -S,
    w: S, d: S * 1.2,
    color: 0xE63946,
    accentColor: '#E63946',
    icon: '🚑',
    equipmentIds: ['camilla-transporte', 'desfibrilador-portatil', 'monitor-transporte', 'mochila-trauma'],
  },
  {
    id: AREA_IDS.URGENCIAS,
    name: 'Urgencias',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    cx: -2 * S, cz: S * 0.5,
    w: S, d: S,
    color: 0xE63946,
    accentColor: '#E63946',
    icon: '🚨',
    equipmentIds: ['camilla-urgencias', 'carro-rojo', 'desfibrilador-bifasico', 'monitor-vital', 'aspirador-portatil'],
  },
  {
    id: AREA_IDS.QUIROFANO,
    name: 'Quirófano',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    cx: -S * 0.5, cz: S * 0.5,
    w: S * 1.2, d: S,
    color: 0x2DC653,
    accentColor: '#2DC653',
    icon: '🔬',
    equipmentIds: ['mesa-quirurgica', 'lampara-cielitica', 'torre-laparoscopia', 'maquina-anestesia', 'electrocauterio', 'monitor-qx'],
  },
  {
    id: AREA_IDS.TRANSPORTE_INT,
    name: 'Transporte Interno',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    cx: S * 0.5, cz: -S * 0.7,
    w: S * 0.8, d: S * 0.7,
    color: 0xF4A261,
    accentColor: '#F4A261',
    icon: '🛏️',
    equipmentIds: ['silla-ruedas', 'camilla-traslado', 'carrito-medicamentos'],
  },
  {
    id: AREA_IDS.TERAPIA_INT,
    name: 'Terapia Intermedia',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    cx: 2 * S, cz: S * 0.5,
    w: S, d: S,
    color: 0x0077B6,
    accentColor: '#0077B6',
    icon: '🫀',
    equipmentIds: ['cama-electrica-ti', 'monitor-multiparametrico', 'oximetro', 'ventilador-ti'],
  },
  {
    id: AREA_IDS.ENDOSCOPIA,
    name: 'Endoscopia',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    cx: 2 * S, cz: -S * 0.7,
    w: S, d: S * 0.8,
    color: 0x9B5DE5,
    accentColor: '#9B5DE5',
    icon: '🔭',
    equipmentIds: ['torre-endoscopia', 'gastroscopio', 'colonoscopio', 'monitor-hd-endo'],
  },
  {
    id: AREA_IDS.SUMINISTRO_GAS,
    name: 'Suministro de Gas',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    cx: S * 0.5, cz: S * 1.8,
    w: S * 0.9, d: S * 0.7,
    color: 0x4CC9F0,
    accentColor: '#4CC9F0',
    icon: '⚗️',
    equipmentIds: ['tanque-oxigeno', 'tanque-co2', 'regulador-presion', 'manifold-gas'],
  },
  {
    id: AREA_IDS.CONCEPCION,
    name: 'Concepción & Gestión',
    floor: 'GROUND',
    y: FLOOR_Y.GROUND,
    cx: -2 * S, cz: S * 1.8,
    w: S, d: S * 0.7,
    color: 0x6C757D,
    accentColor: '#6C757D',
    icon: '📐',
    equipmentIds: ['estacion-trabajo', 'mobiliario-clinico', 'pantalla-presentacion'],
  },

  // ─── PLANTA ALTA ──────────────────────────────────────────
  {
    id: AREA_IDS.TOCO_CIRUGIA,
    name: 'Sala de Toco Cirugía',
    floor: 'UPPER',
    y: FLOOR_Y.UPPER,
    cx: -3 * S, cz: -S * 0.5,
    w: S, d: S,
    color: 0xFF6B9D,
    accentColor: '#FF6B9D',
    icon: '👶',
    equipmentIds: ['mesa-parto', 'monitor-fetal', 'incubadora-neonatal', 'cuna-termica', 'aspirador-neonatal'],
  },
  {
    id: AREA_IDS.UCIN_UTIP,
    name: 'UCIN / UTIP',
    floor: 'UPPER',
    y: FLOOR_Y.UPPER,
    cx: -S, cz: -S * 0.5,
    w: S, d: S,
    color: 0xFF9F1C,
    accentColor: '#FF9F1C',
    icon: '🍼',
    equipmentIds: ['incubadora-neonatal-2', 'ventilador-neonatal', 'bomba-infusion-neonatal', 'monitor-neonatal', 'fototerapia'],
  },
  {
    id: AREA_IDS.TELEMEDICINA,
    name: 'Telemedicina',
    floor: 'UPPER',
    y: FLOOR_Y.UPPER,
    cx: S, cz: -S * 0.5,
    w: S * 0.9, d: S * 0.8,
    color: 0x00B4A0,
    accentColor: '#00B4A0',
    icon: '📡',
    equipmentIds: ['estacion-telemedicina', 'camara-hd', 'monitor-diagnostico', 'estetoscopio-digital'],
  },
  {
    id: AREA_IDS.HOSPITALIZACION,
    name: 'Hospitalización',
    floor: 'UPPER',
    y: FLOOR_Y.UPPER,
    cx: 2.5 * S, cz: -S * 0.5,
    w: S, d: S,
    color: 0x48CAE4,
    accentColor: '#48CAE4',
    icon: '🛌',
    equipmentIds: ['cama-hospitalaria', 'monitor-signos', 'bomba-iv', 'riel-suero', 'cama-electrica'],
  },
  {
    id: AREA_IDS.HEMODIALISIS,
    name: 'Hemodiálisis',
    floor: 'UPPER',
    y: FLOOR_Y.UPPER,
    cx: 2.5 * S, cz: S * 0.6,
    w: S, d: S * 0.8,
    color: 0xE05C5C,
    accentColor: '#E05C5C',
    icon: '🩸',
    equipmentIds: ['maquina-hemodialisis', 'sillon-reclinable', 'monitor-hemo', 'purificador-agua'],
  },
  {
    id: AREA_IDS.IMAGENOLOGIA,
    name: 'Imagenología',
    floor: 'UPPER',
    y: FLOOR_Y.UPPER,
    cx: 2.5 * S, cz: S * 1.6,
    w: S, d: S * 0.8,
    color: 0x7B2FBE,
    accentColor: '#7B2FBE',
    icon: '🩻',
    equipmentIds: ['rayos-x', 'tomografo', 'ultrasonido', 'resonancia-magnetica', 'procesador-imagen'],
  },
  {
    id: AREA_IDS.UCI,
    name: 'UCI',
    floor: 'UPPER',
    y: FLOOR_Y.UPPER,
    cx: S * 0.5, cz: S * 0.8,
    w: S * 1.4, d: S * 1.2,
    color: 0x023E8A,
    accentColor: '#023E8A',
    icon: '💉',
    equipmentIds: ['ventilador-mecanico', 'monitor-uci', 'desfibrilador-bifasico-2', 'bomba-jeringa', 'cama-uci', 'capnografo'],
  },
];

// Mapa de acceso rápido por ID
export const AREAS_BY_ID = Object.fromEntries(
  AREA_DEFINITIONS.map(a => [a.id, a])
);

// Área de spawn
export const SPAWN_AREA = AREA_DEFINITIONS.find(a => a.isSpawn);
